---
title: "Binding all student data together"
author: "The Freemasons"
date: "Initiated on 13/12/2019"
output: html_document
---

# Loading package 
```{r}
library(tidyverse)
library(glue)
library(here)
library(countrycode)
```

# Loading data
```{r}
## Reading in the all student data as tibbles and make sure all variables are coded in the correct variable type
dfs_stu_qqq <- tibble(years = seq(2000, 2018, 3)) %>%
  mutate(paths = glue("Data/Output/{years}/{what}.rds", what = "stu_qqq")) %>%
  mutate(data = map(.x = paths,
                    .f = ~ .x %>%
                      here() %>%
                      read_rds() %>%
                      mutate(school_id = as.character(school_id),
                             student_id = as.character(student_id)) %>%
                      mutate_at(c("mother_educ", "father_educ",
                                  "gender", "computer", "internet",
                                  "desk", "room", "dishwasher", "television",
                                  "computer_n", "car", "book"),
                                as.integer) %>%
                      mutate_at(c("math", "science", "read",
                                  "stu_wgt", "wealth", "escs"),
                                as.numeric)))

names(dfs_stu_qqq$data) <- seq(2000, 2018, 3)
student <- bind_rows(dfs_stu_qqq$data, .id = "year")

student %>%
  group_by(year) %>%
  sample_n(2)

unique_country_iso3c = student$country_iso3c %>% unique
country_tbl = tibble(country_iso3c = unique_country_iso3c) %>% 
  left_join(countrycode::codelist %>% 
              dplyr::select(iso3c, country_name = country.name.en, country_full_name = un.name.en), 
            by = c("country_iso3c" = "iso3c"))
## If the iso3c matches multiple names, then we will flag this 
stopifnot(length(unique_country_iso3c) == nrow(country_tbl))

student = student %>% 
  left_join(country_tbl, by = "country_iso3c") %>% 
  mutate(year = as.integer(year),
         country_iso3c = as.factor(country_iso3c),
         country_name = as.factor(country_name),
         country_full_name = as.factor(country_full_name),
         student_id = as.integer(student_id),
         school_id = as.integer(school_id),
         gender = as.factor(gender)) 
```

```{r}
save(student, file = here("Data/Output/student.rda"))
```

# Session Info

```{r}
sessionInfo()
```