---
title: "PISA 2018 Data Import and Manipulation"
author: "Kim Fitter"
date: "12/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(here)
library(tidyverse)
library(haven)
```

Use the Haven package to read in the SPSS files.

```{r read in spss sav files}
list_filenames <- list_files(path=here("/Data/Raw/2018/"), pattern=".sav")

# Student questionnaire data files
stu_qqq <- read_sav(here("/Data/Raw/2018/CY07_MSU_STU_QQQ.sav"),
    col_select = c(CNT,
         CNTSCHID,
         CNTSTUID,
         ST005Q01TA,
         ST007Q01TA,
         ST004D01T,
         ST011Q04TA,
         ST011Q06TA,
         PV1MATH,
         PV1READ,
         PV1SCIE,
<<<<<<< HEAD
         W_FSTUWT,
         ST011Q01TA,
         ST011Q02TA,
         ST011Q11TA,
         ST012Q01TA,
         ST012Q06NA,
         ST013Q01TA,
         WEALTH,
         ESCS
         ))

# Import School questionnaire data file with selected variables
sch_qqq <- read_sav(here("/Data/Raw/2018/CY07_MSU_SCH_QQQ.sav"),
    col_select = c(CNT,
                   CNTSCHID,
                   SC016Q01TA,
                   SC016Q02TA,
                   SC016Q03TA,
                   SC002Q01TA,
                   SC002Q02TA,
                   SC002Q02TA,
                   STRATIO,
                   SC013Q01TA,
                   STAFFSHORT,
                   W_SCHGRNRABWT,
                   SCHSIZE))

=======
         W_FSTUWT))
# School questionnaire data file
sch_qqq <- read_sav(here("/Data/Raw/2018/CY07_MSU_SCH_QQQ.sav"),n_max = 10)
# Cognitive item data file
stu_cog <- read_sav(here("/Data/Raw/2018/CY07_MSU_STU_COG.sav"),n_max=10) 
#  Questionnaire timing data files 
stu_tim <- read_sav(here("/Data/Raw/2018/CY07_MSU_STU_TIM.sav"),n_max = 10)
# Teacher questionnaire data file
tch_qqq <- read_sav(here("/Data/Raw/2018/CY07_MSU_TCH_QQQ.sav"),n_max = 10)
# Additional data file for Viet Nam
vnm_stu_cog <- read_sav(here("/Data/Raw/2018/CY07_VNM_STU_COG.sav"),n_max = 10)
vnm_stu_pvs <- read_sav(here("/Data/Raw/2018/CY07_VNM_STU_PVS.sav"),n_max = 10)
>>>>>>> b6270c1dfffa7cd1b7bd297789702fa733eab9f3
```

```{r create output files}
stu_qqq_output<- stu_qqq 
sch_qqq_output <- head(sch_qqq)
tch_qqq_output <- head(tch_qqq)
stu_cog_output <- head(stu_cog)
stu_tim_output <- head(stu_tim)
vnm_stu_cog_output <- head(vnm_stu_cog)
vnm_stu_pvs_output <- head(vnm_stu_pvs)
```

```{r view summary}
skimr::skim(stu_qqq_output) 
```


```{r save files output}
# Student questionnaire data files
save(stu_qqq_output, file= here("/Data/Output/2018/CY07_MSU_STU_QQQ.rda"))
# School questionnaire data file
save(sch_qqq_output,file=here("/Data/Output/2018/CY07_MSU_SCH_QQQ.rda"))
# Cognitive item data file
save(stu_cog_output, file=here("/Data/Output/2018/CY07_MSU_STU_COG.rda"))
#  Questionnaire timing data files 
save(stu_tim_output , file= here("/Data/Output/2018/CY07_MSU_STU_TIM.rda"))
# Teacher questionnaire data file
save(tch_qqq_output, file=here("/Data/Output/2018/CY07_MSU_TCH_QQQ.rda"))
# Additional data file for Viet Nam
save(vnm_stu_cog_output, file=(here("/Data/Output/2018/CY07_VNM_STU_COG.rda")))
save(vnm_stu_pvs_output,file=here("/Data/Output/2018/CY07_VNM_STU_PVS.rda"))
```

head(d_sub_2009)

country_sum <- d_sub_2009 %>%
                group_by(CNT) %>%
                summarize(avg_math = mean(PV1MATH)) %>% 
                ggplot(aes(x = CNT, y = avg_math)) +
                  geom_point()

