---
title: "Binding all School data together"
author: "The Freemasons"
date: "`r paste0('Initiated on 2020 May 16, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 10
    fig_width: 10
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
editor_options: 
  chunk_output_type: console
---


# Loading package 
```{r}
library(tidyverse)
library(glue)
library(here)
library(janitor)
library(skimr)
library(haven)

public1private2 = function(x){
  x = as.integer(x)
  case_when(
    x == 1 ~ "public",
    x == 2 ~ "private",
    TRUE ~ NA_character_) %>% as.factor()
}
```

# Curating each data
Since the column names of each of the data are not consistent as of 16 May 2020, ref commit 96a1d8c55c5f17b22526e8e68c0bfd30799911eb, I will load each data by itself, clean and assemble at the end. 

See the Google Sheet for the commonly agreed variables. 

## 2000

```{r}
sch_2000 = read_rds(here("Data/Output/2000/sch_qqq.rds"))
glimpse(sch_2000)

clean_2000 = sch_2000 %>% dplyr::transmute(
  country = cnt %>% as.factor(),
  school_id = schoolid %>% as.factor(), 
  fund_gov = sc04q01 %>% as.numeric(),
  fund_fees = sc04q02 %>% as.numeric(),
  fund_donation = sc04q03 %>% as.numeric(),
  enrol_boys = sc02q01 %>% as.numeric(),
  enrol_girls = sc02q02 %>% as.numeric(),
  stratio = stratio %>% as.numeric(),
  public_private = sc03q01 %>% public1private2(),
  staff_shortage = tcshort %>% as.numeric(),
  sch_wgt = wnrschbw %>% as.numeric(),
  school_size = schlsize %>% as.numeric())

skimr::skim(clean_2000)
```


## 2003
```{r}
sch_2003 = read_rds(here("Data/Output/2003/sch_qqq.rds"))
glimpse(sch_2003)

clean_2003 = sch_2003 %>% dplyr::transmute(
  country = country_iso3c %>% as.factor(),
  school_id = school_id %>% as.factor(), 
  fund_gov = funding_gov %>% as.numeric() %>% na_if(997) %>% na_if(998) %>% na_if(999),
  fund_fees = funding_fees %>% as.numeric() %>% na_if(997) %>% na_if(998) %>% na_if(999),
  fund_donation = funding_donations %>% as.numeric() %>% na_if(997) %>% na_if(998) %>% na_if(999),
  enrol_boys = enrolment_boys %>% as.numeric(),
  enrol_girls = enrolment_girls %>% as.numeric(),
  stratio = student_teacher_ratio %>% as.numeric() %>% na_if(997) %>% na_if(998) %>% na_if(999),
  public_private = public_private %>% public1private2(),
  staff_shortage = staff_shortage %>% as.numeric() %>% na_if(997) %>% na_if(998) %>% na_if(999),
  sch_wgt = sch_wgt %>% as.numeric(),
  school_size = school_size %>% as.numeric() %>% na_if(99997) %>% na_if(99998) %>% na_if(99999))

skimr::skim(clean_2003)
```



## 2006
```{r}
sch_2006 = read_rds(here("Data/Output/2006/sch_qqq.rds"))
glimpse(sch_2006)

clean_2006 = sch_2006 %>% dplyr::transmute(
  country = CNT %>% as.factor(),
  school_id = SCHOOLID %>% as.factor(), 
  fund_gov = SC03Q01 %>% as.numeric() %>% na_if(9997) %>% na_if(9998) %>% na_if(9999),
  fund_fees = SC03Q02 %>% as.numeric() %>% na_if(9997) %>% na_if(9998) %>% na_if(9999),
  fund_donation = SC03Q03 %>% as.numeric() %>% na_if(9997) %>% na_if(9998) %>% na_if(9999),
  enrol_boys = SC01Q01 %>% as.numeric() %>% na_if(9997) %>% na_if(9998) %>% na_if(9999),
  enrol_girls = SC01Q02 %>% as.numeric() %>% na_if(9997) %>% na_if(9998) %>% na_if(9999),
  stratio = STRATIO %>% as.numeric() %>% na_if(9997) %>% na_if(9998) %>% na_if(9999),
  public_private = SC02Q01 %>% public1private2(),
  staff_shortage = TCSHORT %>% as.numeric() %>% na_if(997) %>% na_if(998) %>% na_if(999),
  sch_wgt = W_FSCHWT %>% as.numeric(),
  school_size = SCHSIZE %>% as.numeric() %>% na_if(99997) %>% na_if(99998) %>% na_if(99999))

skimr::skim(clean_2006)
```

## 2009
```{r}
sch_2009 = read_rds(here("Data/Output/2009/sch_qqq.rds"))
glimpse(sch_2009)

clean_2009 = sch_2009 %>% dplyr::transmute(
  country = country %>% as.factor(),
  school_id = school_id %>% as.factor(), 
  fund_gov = fund_gov %>% as.numeric() %>% na_if(9997) %>% na_if(9998) %>% na_if(9999),
  fund_fees = fund_fees %>% as.numeric() %>% na_if(9997) %>% na_if(9998) %>% na_if(9999),
  fund_donation = fund_donation %>% as.numeric() %>% na_if(9997) %>% na_if(9998) %>% na_if(9999),
  enrol_boys = enrol_boys %>% as.numeric() %>% na_if(9997) %>% na_if(9998) %>% na_if(9999),
  enrol_girls = enrol_girls %>% as.numeric() %>% na_if(9997) %>% na_if(9998) %>% na_if(9999),
  stratio = stratio %>% as.numeric() %>% na_if(9997) %>% na_if(9998) %>% na_if(9999),
  public_private = public_private %>% public1private2(),
  staff_shortage = staff_shortage %>% as.numeric() %>% na_if(9997) %>% na_if(9998) %>% na_if(9999),
  sch_wgt = sch_wgt %>% as.numeric(),
  school_size = school_size %>% as.numeric() %>% na_if(99997) %>% na_if(99998) %>% na_if(99999))

skimr::skim(clean_2009)
```

## 2012

```{r}
sch_2012 = read_rds(here("Data/Output/2012/sch_qqq.rds"))
glimpse(sch_2012)

clean_2012 = sch_2012 %>% dplyr::transmute(
  country = CNT %>% as.factor(),
  school_id = SCHOOLID %>% as.factor(), 
  fund_gov = SC02Q01 %>% as.numeric() %>% na_if(9997) %>% na_if(9998) %>% na_if(9999),
  fund_fees = SC02Q02 %>% as.numeric() %>% na_if(9997) %>% na_if(9998) %>% na_if(9999),
  fund_donation = SC02Q03 %>% as.numeric() %>% na_if(9997) %>% na_if(9998) %>% na_if(9999),
  enrol_boys = SC07Q01 %>% as.numeric() %>% na_if(9997) %>% na_if(9998) %>% na_if(9999),
  enrol_girls = SC07Q02 %>% as.numeric() %>% na_if(9997) %>% na_if(9998) %>% na_if(9999),
  stratio = STRATIO %>% as.numeric() %>% na_if(9997) %>% na_if(9998) %>% na_if(9999),
  public_private = SC01Q01 %>% public1private2(),
  staff_shortage = TCSHORT %>% as.numeric() %>% na_if(9997) %>% na_if(9998) %>% na_if(9999),
  sch_wgt = W_FSCHWT %>% as.numeric(),
  school_size = SCHSIZE %>% as.numeric() %>% na_if(99997) %>% na_if(99998) %>% na_if(99999))

skimr::skim(clean_2012)
```

## 2015

```{r}
sch_2015 = read_rds(here("Data/Output/2015/sch_qqq.rds"))
glimpse(sch_2015)

clean_2015 = sch_2015 %>% dplyr::transmute(
  country = CNT %>% as.factor(),
  school_id = CNTSCHID %>% as.factor(), 
  fund_gov = SC016Q01TA %>% as.numeric(),
  fund_fees = SC016Q02TA %>% as.numeric(),
  fund_donation = SC016Q03TA %>% as.numeric(),
  enrol_boys = SC002Q01TA %>% as.numeric(),
  enrol_girls = SC002Q02TA %>% as.numeric(),
  stratio = STRATIO %>% as.numeric(),
  public_private = SC013Q01TA %>% public1private2(),
  staff_shortage = STAFFSHORT %>% as.numeric(),
  sch_wgt = W_SCHGRNRABWT %>% as.numeric(),
  school_size = SCHSIZE %>% as.numeric())

skimr::skim(clean_2015)
```


## 2018

```{r}
sch_2018 = read_rds(here("Data/Output/2018/sch_qqq.rds"))
glimpse(sch_2018)

clean_2018 = sch_2018 %>% dplyr::transmute(
  country = CNT %>% as.factor(),
  school_id = CNTSCHID %>% as.factor(), 
  fund_gov = SC016Q01TA %>% as.numeric(),
  fund_fees = SC016Q02TA %>% as.numeric(),
  fund_donation = SC016Q03TA %>% as.numeric(),
  enrol_boys = SC002Q01TA %>% as.numeric(),
  enrol_girls = SC002Q02TA %>% as.numeric(),
  stratio = STRATIO %>% as.numeric(),
  public_private = SC013Q01TA %>% public1private2(),
  staff_shortage = STAFFSHORT %>% as.numeric(),
  sch_wgt = W_SCHGRNRABWT %>% as.numeric(),
  school_size = SCHSIZE %>% as.numeric())

skimr::skim(clean_2018)
```

## 2022

```{r}
sch_2022 = read_rds(here("Data/Output/2022/sch_qqq.rds"))
glimpse(sch_2022)

clean_2022 = sch_2022 %>% dplyr::transmute(
  country = CNT %>% as.character(),
  school_id = CNTSCHID %>% as.factor(),
  public_private = SC013Q01TA %>% public1private2(),
  fund_gov = SC016Q01TA %>% as.numeric(),
  fund_fees = SC016Q02TA %>% as.numeric(),
  fund_donation = SC016Q03TA %>% as.numeric(),
  enrol_boys = SC002Q01TA %>% as.numeric(),
  enrol_girls = SC002Q02TA %>% as.numeric(),
  stratio = STRATIO %>% as.numeric(),
  staff_shortage = STAFFSHORT %>% as.numeric(),
  sch_wgt = W_SCHGRNRABWT %>% as.numeric(),
  school_size = SCHSIZE %>% as.numeric()) %>% 
  mutate(across(everything(), ~ ifelse(is.infinite(.), NA, .)))

skimr::skim(clean_2022)
```


# Binding data

```{r}
# Ensure all datasets have the same type for school_id and public_private before binding (converting to character)
list_data <- lst(clean_2000, clean_2003, clean_2006, clean_2009, clean_2012, clean_2015, clean_2018, clean_2022)

# Remove "clean_" from the names
names(list_data) <- names(list_data) %>% str_remove("clean_")

# Convert both school_id and public_private to character in each dataset to avoid type conflicts
list_data <- list_data %>%
  map(~ .x %>% 
        mutate(
          school_id = as.integer(school_id),
          public_private = as.character(public_private)  # Convert public_private to character
        ))

# Bind the rows and convert character columns to factors
school <- list_data %>%
  bind_rows(.id = "year") %>%
  dplyr::mutate(public_private = as.factor(public_private)) %>%  # Convert public_private back to factor
  dplyr::mutate_if(is.character, as.factor) %>%
  as_tibble()

# Skim the data to inspect
skimr::skim(school)
```


# Saving full sized data (rda file)

```{r}
full_data_transfer_folder = "Data/Output/Transfer/data"
dir.create(here(full_data_transfer_folder), recursive = TRUE, showWarnings = FALSE)
save(school, file = here(full_data_transfer_folder, "school.rda"), compress = "xz")
```

# Creating heatmap for README

```{r, fig.height=6, fig.width=12}
# Summarize missingness for each column by year
missing_summary <- school %>%
  group_by(year) %>%                                  
  summarize(across(everything(),                   
                   ~ sum(is.na(.)) / n(),          
                   .names = "missing_{col}")) %>%  
  pivot_longer(cols = starts_with("missing_"),
               names_to = "column", 
               values_to = "missing_percentage") %>%
  mutate(column = str_remove(column, "missing_"),
         label_missing_percentage = scales::percent(missing_percentage, accuracy = 0.1)) 

# View the summary
missing_summary

p = missing_summary %>%
  ggplot(aes(x = year, 
             y = column, 
             label = label_missing_percentage,
             fill = missing_percentage)) +
  geom_tile() +
  geom_text() +
  scale_fill_gradient2(
    low = "white", 
    high = "#287afc",
    breaks = c(0, 0.5, 1),
    labels = scales::label_percent()) +
  labs(title = "Missingness Percentage in the School Data by Variables and Year",
       x = "Year",
       y = "Variables", 
       fill = "Missing Percentage") +
  theme_minimal() +
  theme(legend.position = "bottom")

print(p)

ggsave(plot = p, 
       filename = here("Data/Output/Transfer/README_school_data_missing_values_summary.png"), height = 6, width = 12)
```


# Session Info

```{r}
sessionInfo()
```