---
title: "Student Quality Checks before binding"
author: "The Freemasons"
date: "`r paste0('Initiated on 2019 Dec 13, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 10
    fig_width: 10
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
editor_options: 
  chunk_output_type: console
---

# Loading package 
```{r}
library(tidyverse)
library(glue)
library(here)
library(haven)
```

```{r}
yes1no2 = function(x){
  x = as.integer(x)
  case_when(
    x == 1 ~ "yes",
    x == 2 ~ "no",
    TRUE ~ NA_character_) %>% as.factor()
}

none1one2two3threemore4 = function(x){
  x = as.integer(x)
  case_when(
    x == 1 ~ "0", 
    x == 2 ~ "1",
    x == 3 ~ "2",
    x == 4 ~ "3+",
    TRUE ~ NA_character_) %>% as.factor()
}

iscednone1 = function(x){
  x = as.integer(x)
  case_when(
    x == 1 ~ "less than ISCED1", 
    x == 2 ~ "ISCED 1",
    x == 3 ~ "ISCED 2",
    x == 4 ~ "ISCED 3B, C",
    x == 5 ~ "ISCED 3A",
    TRUE ~ NA_character_) %>% as.factor()
}

isced3a1 = function(x){
  x = as.integer(x)
  case_when(
    x == 1 ~ "ISCED 3A", 
    x == 2 ~ "ISCED 3B, C",
    x == 3 ~ "ISCED 2",
    x == 4 ~ "ISCED 1",
    x == 5 ~ "less than ISCED1",
    TRUE ~ NA_character_) %>% as.factor()
}

fe1ma2 = function(x){
  x = as.integer(x)
  case_when(
    x == 1 ~ "female",
    x == 2 ~ "male",
    TRUE ~ NA_character_) %>% as.factor()
}
```


# 2000 data
```{r}
stu_2000 = read_rds(here("Data/Output/2000/stu_qqq.rds"))

clean_2000 = stu_2000 %>% 
  dplyr::transmute(
    country = country_iso3c %>% as.factor(),
    school_id = school_id |> as.character(),
    student_id = student_id |> as.integer(),
    mother_educ = mother_educ %>% as.factor(), ## This is all missing in 2000
    father_educ = father_educ %>% as.factor(), ## This is all missing in 2000
    gender = gender %>% fe1ma2(),
    computer = computer %>% as.factor(), ## This is all missing in 2000
    internet = internet %>% yes1no2(),
    math, 
    read, 
    science, 
    stu_wgt, 
    desk = desk %>% yes1no2(),
    room = room %>% yes1no2(),
    dishwasher = dishwasher %>% yes1no2(),
    television = television %>% none1one2two3threemore4(), 
    computer_n = computer_n %>% none1one2two3threemore4(), 
    car = car %>% none1one2two3threemore4(),
    book = case_when(
      book == 1 ~ "none",
      book == 2 ~ "1-10",
      book == 3 ~ "11-50",
      book == 4 ~ "51-100",
      book == 5 ~ "101-250",
      book == 6 ~ "251-500",
      book == 7 ~ "more than 500",
      TRUE ~ NA_character_
    ) %>% as.factor(),
    wealth, 
    escs)


skimr::skim(clean_2000)
```



# 2003 data
```{r}
stu_2003 = read_rds(here("Data/Output/2003/stu_qqq.rds"))

clean_2003 = stu_2003 %>% 
  dplyr::transmute(
    country = country_iso3c %>% as.factor(),
    school_id = school_id |> as.character(),
    student_id = student_id |> as.integer(),
    mother_educ = mother_educ %>% iscednone1(),
    father_educ = father_educ %>% iscednone1(),
    gender = gender %>% fe1ma2(),
    computer = computer %>% yes1no2(), ## This is a wrong column, see Google Sheets
    internet = internet %>% yes1no2(),
    math = math %>% as.numeric(), 
    read = read %>% as.numeric(), 
    science = science %>% as.numeric(), 
    stu_wgt = stu_wgt %>% as.numeric(), 
    desk = desk %>% yes1no2(),
    room = room %>% yes1no2(),
    dishwasher = dishwasher %>% yes1no2(),
    television = television %>% none1one2two3threemore4(), 
    computer_n = computer_n %>% none1one2two3threemore4(), 
    car = car %>% none1one2two3threemore4(),
    book = case_when(
      book == 1 ~ "0-10",
      book == 2 ~ "11-25",
      book == 3 ~ "26-100",
      book == 4 ~ "101-200",
      book == 5 ~ "201-500",
      book == 6 ~ "more than 500",
      TRUE ~ NA_character_
    ) %>% as.factor(),
    wealth, 
    escs = escs %>% as.numeric %>% na_if(999))


skimr::skim(clean_2003)
```


# 2006 data
```{r}
stu_2006 = read_rds(here("Data/Output/2006/stu_qqq.rds"))

clean_2006 = stu_2006 %>% 
  dplyr::transmute(
    country = country_iso3c %>% as.factor(),
    school_id = school_id |> as.character(),
    student_id = student_id |> as.integer(),
    mother_educ = mother_educ %>% isced3a1(),
    father_educ = father_educ %>% isced3a1(),
    gender = gender %>% fe1ma2(),
    computer = computer %>% yes1no2(),
    internet = internet %>% yes1no2(),
    math, 
    read = read %>% na_if(9997), 
    science, 
    stu_wgt, 
    desk = desk %>% yes1no2(),
    room = room %>% yes1no2(),
    dishwasher = dishwasher %>% yes1no2(),
    television = television %>% none1one2two3threemore4(), 
    computer_n = computer_n %>% none1one2two3threemore4(), 
    car = car %>% none1one2two3threemore4(),
    book = case_when(
      book == 1 ~ "0-10",
      book == 2 ~ "11-25",
      book == 3 ~ "26-100",
      book == 4 ~ "101-200",
      book == 5 ~ "201-500",
      book == 6 ~ "more than 500",
      TRUE ~ NA_character_
    ) %>% as.factor(),
    wealth = wealth %>% na_if(997) %>% na_if(999), 
    escs = escs %>% na_if(997) %>% na_if(999))

skimr::skim(clean_2006)
```


# 2009 data
```{r}
stu_2009 = read_rds(here("Data/Output/2009/stu_qqq.rds"))

clean_2009 = stu_2009 %>% 
  dplyr::transmute(
    country = country_iso3c %>% as.factor(),
    school_id = school_id |> as.character(),
    student_id = student_id |> as.integer(),
    mother_educ = mother_educ %>% isced3a1(),
    father_educ = father_educ %>% isced3a1(),
    gender = gender %>% fe1ma2(),
    computer = computer %>% yes1no2(),
    internet = internet %>% yes1no2(),
    math, 
    read, 
    science, 
    stu_wgt, 
    desk = desk %>% yes1no2(),
    room = room %>% yes1no2(),
    dishwasher = dishwasher %>% yes1no2(),
    television = television %>% none1one2two3threemore4(), 
    computer_n = computer_n %>% none1one2two3threemore4(), 
    car = car %>% none1one2two3threemore4(),
    book = case_when(
      book == 1 ~ "0-10",
      book == 2 ~ "11-25",
      book == 3 ~ "26-100",
      book == 4 ~ "101-200",
      book == 5 ~ "201-500",
      book == 6 ~ "more than 500",
      TRUE ~ NA_character_
    ) %>% as.factor(),
    wealth = wealth %>% na_if(9997) %>% na_if(9999), 
    escs = escs %>% na_if(9997) %>% na_if(9999))

skimr::skim(clean_2009)
```



# 2012 data
```{r}
stu_2012 = read_rds(here("Data/Output/2012/stu_qqq.rds"))

clean_2012 = stu_2012 %>% 
  dplyr::transmute(
    country = country_iso3c %>% as.factor(),
    school_id = school_id |> as.character(),
    student_id = student_id |> as.integer(),
    mother_educ = mother_educ %>% isced3a1(),
    father_educ = father_educ %>% isced3a1(),
    gender = gender %>% fe1ma2(),
    computer = computer %>% yes1no2(),
    internet = internet %>% yes1no2(),
    math, 
    read, 
    science, 
    stu_wgt, 
    desk = desk %>% yes1no2(),
    room = room %>% yes1no2(),
    dishwasher = dishwasher %>% yes1no2(),
    television = television %>% none1one2two3threemore4(), 
    computer_n = computer_n %>% none1one2two3threemore4(), 
    car = car %>% none1one2two3threemore4(),
    book = case_when(
      book == 1 ~ "0-10",
      book == 2 ~ "11-25",
      book == 3 ~ "26-100",
      book == 4 ~ "101-200",
      book == 5 ~ "201-500",
      book == 6 ~ "more than 500",
      TRUE ~ NA_character_
    ) %>% as.factor(),
    wealth = wealth %>% na_if(9997) %>% na_if(9999), 
    escs = escs %>% na_if(9997) %>% na_if(9999))

skimr::skim(clean_2012)
```


# 2015 data
```{r}
stu_2015 = read_rds(here("Data/Output/2015/stu_qqq.rds"))

clean_2015 = stu_2015 %>% 
  dplyr::transmute(
    country = country_iso3c %>% as.factor(),
    school_id = school_id |> as.character(),
    student_id = student_id |> as.integer(),
    mother_educ = mother_educ %>% isced3a1(),
    father_educ = father_educ %>% isced3a1(),
    gender = gender %>% fe1ma2(),
    computer = computer %>% yes1no2(),
    internet = internet %>% yes1no2(),
    math, 
    read, 
    science, 
    stu_wgt, 
    desk = desk %>% yes1no2(),
    room = room %>% yes1no2(),
    dishwasher = dishwasher %>% yes1no2(), ## This is all NA because the storage of this variable was very problematic
    television = television %>% none1one2two3threemore4(), 
    computer_n = computer_n %>% none1one2two3threemore4(), 
    car = car %>% none1one2two3threemore4(),
    book = case_when(
      book == 1 ~ "0-10",
      book == 2 ~ "11-25",
      book == 3 ~ "26-100",
      book == 4 ~ "101-200",
      book == 5 ~ "201-500",
      book == 6 ~ "more than 500",
      TRUE ~ NA_character_
    ) %>% as.factor(),
    wealth = wealth %>% na_if(9997) %>% na_if(9999), 
    escs = escs %>% na_if(9997) %>% na_if(9999))

skimr::skim(clean_2015)
```


# 2018 data
```{r}
stu_2018 = read_rds(here("Data/Output/2018/stu_qqq.rds"))

clean_2018 = stu_2018 %>% 
  dplyr::transmute(
    country = country_iso3c %>% as.factor(),
    school_id = school_id |> as.character(),
    student_id = student_id |> as.integer(),
    mother_educ = mother_educ %>% isced3a1(),
    father_educ = father_educ %>% isced3a1(),
    gender = gender %>% fe1ma2(),
    computer = computer %>% yes1no2(),
    internet = internet %>% yes1no2(),
    math, 
    read, 
    science, 
    stu_wgt, 
    desk = desk %>% yes1no2(),
    room = room %>% yes1no2(),
    dishwasher = dishwasher %>% yes1no2(), ## This is all NA because the storage of this variable was very problematic, see issue 7
    television = television %>% none1one2two3threemore4(), 
    computer_n = computer_n %>% none1one2two3threemore4(), 
    car = car %>% none1one2two3threemore4(),
    book = case_when(
      book == 1 ~ "0-10",
      book == 2 ~ "11-25",
      book == 3 ~ "26-100",
      book == 4 ~ "101-200",
      book == 5 ~ "201-500",
      book == 6 ~ "more than 500",
      TRUE ~ NA_character_
    ) %>% as.factor(),
    wealth = wealth %>% as.numeric %>% na_if(95) %>% na_if(97) %>% na_if(98) %>% na_if(99), 
    escs = escs %>% as.numeric %>% na_if(95) %>% na_if(97) %>% na_if(98) %>% na_if(99))

skimr::skim(clean_2018)
```

# 2022 data
```{r}
stu_2022 <- read_rds(here("Data/Output/2022/stu_qqq.rds"))

clean_2022 <- stu_2022 %>% 
  dplyr::transmute(
    country = country_iso3c %>% as.factor(),
    school_id = school_id |> as.character(),
    student_id = student_id |> as.integer(),
    mother_educ = mother_educ %>% isced3a1(),
    father_educ = father_educ %>% isced3a1(),
    gender = gender %>% fe1ma2(),
    computer = computer %>% yes1no2(),
    internet = internet %>% yes1no2(),
    math, 
    read, 
    science, 
    stu_wgt, 
    desk = desk %>% yes1no2(),             ## This is all NA
    room = room %>% yes1no2(),
    dishwasher = dishwasher %>% yes1no2(), ## This is all NA 
    television = television %>% none1one2two3threemore4(), 
    computer_n = computer_n %>% none1one2two3threemore4(), 
    # laptop_n = laptop_n %>% none1one2two3threemore4(),
    car = car %>% none1one2two3threemore4(),
    book = case_when(
      book == 1 ~ "0-10",
      book == 2 ~ "11-25",
      book == 3 ~ "26-100",
      book == 4 ~ "101-200",
      book == 5 ~ "201-500",
      book == 6 ~ "more than 500",
      TRUE ~ NA_character_
    ) %>% as.factor(),
    wealth = wealth %>% as.numeric %>% na_if(95) %>% na_if(97) %>% na_if(98) %>% na_if(99),  ## This is all NA
    escs = escs %>% as.numeric %>% na_if(95) %>% na_if(97) %>% na_if(98) %>% na_if(99))

skimr::skim(clean_2022)
```

```{r}
list_data <- list(
  "2000" = clean_2000,
  "2003" = clean_2003,
  "2006" = clean_2006,
  "2009" = clean_2009,
  "2012" = clean_2012,
  "2015" = clean_2015,
  "2018" = clean_2018,
  "2022" = clean_2022
)

names(list_data) = names(list_data) %>% str_remove("clean_")

list_data = purrr::map2(
  .x = list_data,  
  .y = names(list_data),
  .f = ~ .x |> 
    dplyr::mutate(year = .y) |> 
    as_tibble() |> 
    dplyr::select(year, everything()) |> 
    dplyr::mutate(year = as.integer(year))
)

## Checking binding can work
all_student_data = bind_rows(list_data)
```

# Saving full sized data (rds file)

```{r}
full_data_transfer_folder = "Data/Output/Transfer/student_full_data"
dir.create(here(full_data_transfer_folder), recursive = TRUE, showWarnings = FALSE)

# Save the RDS files using list_data and their respective keys
saveRDS(list_data[["2000"]], here(full_data_transfer_folder, "student_2000.rds"), compress = "xz")
saveRDS(list_data[["2003"]], here(full_data_transfer_folder, "student_2003.rds"), compress = "xz")
saveRDS(list_data[["2006"]], here(full_data_transfer_folder, "student_2006.rds"), compress = "xz")
saveRDS(list_data[["2009"]], here(full_data_transfer_folder, "student_2009.rds"), compress = "xz")
saveRDS(list_data[["2012"]], here(full_data_transfer_folder, "student_2012.rds"), compress = "xz")
saveRDS(list_data[["2015"]], here(full_data_transfer_folder, "student_2015.rds"), compress = "xz")
saveRDS(list_data[["2018"]], here(full_data_transfer_folder, "student_2018.rds"), compress = "xz")
saveRDS(list_data[["2022"]], here(full_data_transfer_folder, "student_2022.rds"), compress = "xz")
```

# Saving subset data (rda data files)
```{r}
OECD_countries = c(
  "AUS", "AUT", "BEL", "CAN", "CHL",
  "COL", "CZE", "DNK", "EST", "FIN",
  "FRA", "DEU", "GRC", "HUN", "ISL",
  "IRL", "ISR", "ITA", "JPN", "KOR",
  "LVA", "LTU", "LUX", "MEX", "NLD",
  "NZL", "NOR", "POL", "PRT", "SVK",
  "SVN", "ESP", "SWE", "CHE", "TUR",
  "GBR", "USA", "CRI")

stopifnot(nrow(OECD_countries) == 38)


sampling_student_data = function(full_data){
  set.seed(2024)
  
  subset_data <- full_data %>%
    dplyr::filter(country %in% OECD_countries) |>
    dplyr::group_by(country) %>%
    dplyr::sample_n(size = 50) %>%
    dplyr::ungroup()
  
  return(subset_data)
}
```

```{r}
subset_data_transfer_folder = "Data/Output/Transfer/data"
dir.create(here(subset_data_transfer_folder), recursive = TRUE, showWarnings = FALSE)

# Individual lines of code for each year
message("Processing student data for the year: 2000")
student_subset_2000 <- sampling_student_data(list_data[["2000"]])
save(student_subset_2000, file = here(subset_data_transfer_folder, "student_subset_2000.rda"), compress = "xz")

message("Processing student data for the year: 2003")
student_subset_2003 <- sampling_student_data(list_data[["2003"]])
save(student_subset_2003, file = here(subset_data_transfer_folder, "student_subset_2003.rda"), compress = "xz")

message("Processing student data for the year: 2006")
student_subset_2006 <- sampling_student_data(list_data[["2006"]])
save(student_subset_2006, file = here(subset_data_transfer_folder, "student_subset_2006.rda"), compress = "xz")

message("Processing student data for the year: 2009")
student_subset_2009 <- sampling_student_data(list_data[["2009"]])
save(student_subset_2009, file = here(subset_data_transfer_folder, "student_subset_2009.rda"), compress = "xz")

message("Processing student data for the year: 2012")
student_subset_2012 <- sampling_student_data(list_data[["2012"]])
save(student_subset_2012, file = here(subset_data_transfer_folder, "student_subset_2012.rda"), compress = "xz")

message("Processing student data for the year: 2015")
student_subset_2015 <- sampling_student_data(list_data[["2015"]])
save(student_subset_2015, file = here(subset_data_transfer_folder, "student_subset_2015.rda"), compress = "xz")

message("Processing student data for the year: 2018")
student_subset_2018 <- sampling_student_data(list_data[["2018"]])
save(student_subset_2018, file = here(subset_data_transfer_folder, "student_subset_2018.rda"), compress = "xz")

message("Processing student data for the year: 2022")
student_subset_2022 <- sampling_student_data(list_data[["2022"]])
save(student_subset_2022, file = here(subset_data_transfer_folder, "student_subset_2022.rda"), compress = "xz")
```

# Creating heatmap for README

```{r, fig.height=6, fig.width=12}
# Summarize missingness for each column by year
missing_summary <- all_student_data %>%
  group_by(year) %>%                                  
  summarize(across(everything(),                   
                   ~ sum(is.na(.)) / n(),          
                   .names = "missing_{col}")) %>%  
  pivot_longer(cols = starts_with("missing_"),
               names_to = "column", 
               values_to = "missing_percentage") %>%
  mutate(column = str_remove(column, "missing_"),
         label_missing_percentage = scales::percent(missing_percentage, accuracy = 0.1)) 

# View the summary
missing_summary

p = missing_summary %>%
  ggplot(aes(x = factor(year), 
             y = column, 
             label = label_missing_percentage,
             fill = missing_percentage)) +
  geom_tile() +
  geom_text() +
  scale_fill_gradient2(
    low = "white", 
    high = "#287afc",
    breaks = c(0, 0.5, 1),
    labels = scales::label_percent()) +
    scale_x_discrete(breaks = c(2000, 2003, 2006, 2009, 2012, 2015, 2018, 2022)) +
  labs(title = "Missingness Percentage in the Student Data by Variables and Year",
       x = "Year",
       y = "Variables", 
       fill = "Missing Percentage") +
  theme_minimal() +
  theme(legend.position = "bottom")

print(p)

ggsave(plot = p, 
       filename = here("Data/Output/Transfer/README_student_data_missing_values_summary.png"), height = 6, width = 12)
```

# Session info
```{r}
sessioninfo::session_info()
```

